### ISSUE TITLE
how are mongo entries deleted when they expire ?

### ISSUE THREAD

**Issue by dcolens** [cayasso/cacheman-mongo#10]
sounds like the TTL is checked on `get` but what happens if get is not called for an entry, it remains in mongo forever ?

Would it make sense to use mongo's builtin TTL functionality: https://docs.mongodb.org/manual/tutorial/expire-data/ for this ?

The only change required is to create an index and that will ensure 
   * entries in Mongo are always fresh (no need to validate anymore)
   * rotten entries are deleted even if not queried

**Comment by cayasso** [comment]
Your PR https://github.com/cayasso/cacheman-mongo/pull/11 make sense, I just merge it.
Thank for your time!

**Comment by cayasso** [comment]
To answer your questions: yes, I did not have any timer setup for checking expirations, its basically was on demand.
