### ISSUE TITLE
Passing MongoDB Instance Directly as Client Does Not Work

### ISSUE THREAD

**Issue by MrTechCenter** [cayasso/cacheman-mongo#18]
I have a db.js helper file which is used to establish a persistent connection to my MongoDB database that I can reference elsewhere in my program by requiring db.js and calling getDB() which returns the connection string for connecting to my database.

If I pass this connection string in as follows, I get "the options [client] is not supported, the options [database] is not supported, the options [collection] is not supported, the options [hosts] is not supported:

` let CachemanMongo = require('cacheman-mongo');`
` let db = require('../helpers/db).getDB();`
` var cache = new CachemanMongo(db, { collection: 'assetsList_cache' });`

Also, specifying db as the client in the CachemanMongo options returns the same errors:

`var cache = new CachemanMongo({ client: db, collection: 'assetsList_cache' });`

And after throwing these errors, CachemanMongo defaults to trying to connect to a localhost MongoDB instance, which obviously fails since a local instance does not exists.

Passing in an established MongoDB instance in this way had previously worked just fine but no longer does for some reason, and I know that it is not a problem with my database or the way that I am calling the connection string, because I call getDB() to get the connection string in other places in my same program and can interact just fine with my database there. How can I use my existing database instance with CachemanMongo?

**Comment by MrTechCenter** [comment]
Ok, now it gets even weirder. If I declare the cache variable as a `new CachemanMongo(client, {collection: collectionName})`  instance INSIDE of the function that calls `cache.get` or `cache.set` then it accepts my existing MongoDB instance and corresponding collection as parameters for `new CachemanMongo` just fine and doesn't default to trying to connect to a local MongoDB instance. However, this workaround is unacceptable because it will only let you use an existing, defined CachemanMongo instance inside of one function and one function only. If I leave my declaration outside of any functions, but in the same file that `cache.get` and `cache.set` are called, I get the same issues I mentioned above.

**Comment by cayasso** [comment]
@MrTechCenter Can you provide more info on the platform that you are using, for example version of mongodb, OS, etc?

**Comment by MrTechCenter** [comment]
The versions I'm using are as follows:

OS: Windows 10 ENT x64
MongoDB: 3.4.1
Node.Js: 6.11.0
NPM: 3.10.10
Cacheman: 2.2.1
Cacheman-mongo: 1.0.3
Mongodb node module: 2.2.31
Mongodb-core: 2.1.15
Mongodb-uri: 0.9.7

**Comment by MrTechCenter** [comment]
Unsure of what changed, as there haven't been any new commits on this project. But this issue is no longer occurring and I'm able to pass in my existing MongoDB instance as specified above. Thanks cayasso!
