### ISSUE TITLE
Log statements

### ISSUE THREAD

**Issue by thenitai** [cayasso/cacheman-mongo#20]
Hi there,

Switched from Redis to MongoDB with Cacheman. However, there are a lot of the following statements in the console:

```
the options [engine] is not supported
the options [username] is not supported
the options [password] is not supported
the options [host] is not supported
the options [port] is not supported
the options [database] is not supported
the options [collection] is not supported
the options [compression] is not supported
the options [hosts] is not supported
```

Connection itself works and all is good, but wondering what we can do about these statements please.

Thank you.

**Comment by Themandunord** [comment]
+1

**Comment by Themandunord** [comment]
I create a pull request #21

**Comment by cayasso** [comment]
1.0.4 is out with the fix for this issue.
